### ISSUE TITLE
Theming template wrong

### ISSUE THREAD

**Issue by joewheaton** [Riverscapes/riverscapes-website-jekyll#12]
On the [before you start § of the theming instructions](https://riverscapes.xyz/Tools/Technical_Reference/Documentation_Standards/WebSites/theming.html#before-you-start), we sent people to the old [TemplateDocs](https://github.com/Riverscapes/TemplateDocs) repo, which I think is dead (can you confirm @MattReimer or @philipbaileynar?). Shoudn't it refer to [riverscapes-jeklyll-thme](https://github.com/Riverscapes/riverscapes-jekyll-theme)?

**Comment by MattReimer** [comment]
Yup TemplateDocs is dead. Don't use it. Riverscapes-jekyll-theme is what you should use
