### ISSUE TITLE
Add video for BRAT Webinar

### ISSUE THREAD

**Issue by joewheaton** [Riverscapes/riverscapes-website-jekyll#21]
So on our [BRAT Webinar page](https://riverscapes.xyz/About/Community/Events/2021/2021_BRAT_BLM.html#slides--exercises) 

https://github.com/Riverscapes/riverscapes-website/blob/8c22bb4615387106dc5e4fe78cf8261a161bcbc4/About/Community/Events/2021/2021_BRAT_BLM.md?plain=1#L112-L114

We need to get the video(s) in. I'm thinking in that spot, we put a playlist, and we split out the recordings into the rough thematic headings we covered. You can do this however you like, but do be careful to watch the videos and remove any inappropriate discussion(s) (use your judgement). 

Raw videos are [here in box](https://usu.box.com/s/6516zd6v7dwznkrl52tfpnt9czt3ozxj).

**Comment by jtgilbert** [comment]
@joewheaton I need permission to commit to this repo.

**Comment by jtgilbert** [comment]
@joewheaton I'm having an issue. I cloned the repo, checked out a new branch, and added the videos but when I push the commit I get this error:

ERROR: Permission to Riverscapes/riverscapes-website.git denied to jtgilbert.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by joewheaton** [comment]
Sorted by adding access rights for Jordan.
