### ISSUE TITLE
Check updated Home Page

### ISSUE THREAD

**Issue by joewheaton** [Riverscapes/riverscapes-website-jekyll#5]
Hey @philipbaileynar 
I added a new home page to set stage. I tried to frame it in terms of the four primary things we do. See what you think. Its a verbose brain dump... needs editing.

**Comment by philipbaileynar** [comment]
1. Brain dump is PERFECT right now. can refine later. I really like the completely fundamental justification. The call to arms.
1. Hopefully we can drop the mustard buttons above the text once the top menu is functional? (Its not right now because the domain is wrong).
