### ISSUE TITLE
Create data@riverscapes.net email address

### ISSUE THREAD

**Issue by philipbaileynar** [Riverscapes/riverscapes-website-jekyll#51]
Create data@riverscapes.net email address and forward to the following people that @joewheaton identifies

**Comment by MattReimer** [comment]
Hey @philipbaileynar I don't really have to be a middleman here:

<img width="1229" alt="Screenshot 2023-05-02 at 9 27 17 AM" src="https://user-images.githubusercontent.com/1063391/235727413-f6a6a695-cf84-486e-b98b-86516c6cd1a7.png">

<img width="1086" alt="Screenshot 2023-05-02 at 9 26 56 AM" src="https://user-images.githubusercontent.com/1063391/235727697-6fc3f273-b163-4595-9ea3-f3fd42fbead8.png">

**Comment by philipbaileynar** [comment]
Closing this issue in favour of customer support software like FreshDesk.
