### ISSUE TITLE
Review Updated Tools Page

### ISSUE THREAD

**Issue by joewheaton** [Riverscapes/riverscapes-website-jekyll#6]
I updated the [tools](https://riverscapes.github.io/riverscapes-website/Tools/) page substantially ([commit](https://github.com/Riverscapes/riverscapes-website/commit/beba92768454b666815ef99600b7b7fe13b77f7d)). Please read through and see if it makes sense to you. I broke things out into compliant and pending compliant tools (and added a bunch of the collaborators from [here's](https://docs.google.com/document/d/1QKVFkMsmCvY54HqV3H3Bem2LWOFt3QhEibHjWZi0iZE/edit#) tools).

**Comment by philipbaileynar** [comment]
This is definitely heading in the right direction.

Note that by your definition GCD is actually not riverscapes compliant. It does not produce a project.rs.xml.

**Comment by joewheaton** [comment]
Cool.

Excellent point re: GCD. We'll need to cobble some cash together to fix
that.
_____________________
Dr. Joseph M. Wheaton
435-554-1247 (direct) | http://www.joewheaton.org
